### PR TITLE
Implement Area Calculations

### PR DESCRIPTION
**Pull request by reganlaurell**
- Calculate area of a Square, Rectangle, Circle, and Triangle. 
- Throw exception when negative numbers or zero is submitted
- Test Area calculations

### CODE REVIEW

**Review by vbrazo — APPROVED** [review]
Hey, @reganlaurell. This looks good to me. Nice work!

I've noticed that you've contributed a lot to this repository, and I'm going to ask the admin to make you a member to help me maintain this repo. How does that sound to you? (@AnupKumarPanwar cc)

Thanks for contributing!

**Comment by reganlaurell** [comment]
Hello, @vbrazo! That sounds cool! What do I have to do as member and maintainer of the repo?

**Comment by vbrazo** [comment]
@reganlaurell please help me review all the 34 pending Pull Requests and make sure we merge the best code that we can :)

**Comment by vbrazo** [comment]
Feel free to tag me for any help. I'm always around but very busy as always. Cheers.

**Pull request merged**
